# Generated by Django 3.1.4 on 2021-01-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="description",
            field=models.TextField(default="...", max_length=500),
        ),
    ]
