# Generated by Django 3.1.4 on 2021-02-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seller_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
