# Generated by Django 3.1.4 on 2021-02-11 10:58

from django.db import models, migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name='Sellers'),
        Group(name='CommonUsers'),
        Group(name='Guests'),
        Group(name='Moderators'),
    ])


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            "Sellers",
            "CommonUsers",
            'Guests',
            "Moderators"
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210208_1630'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
