# Generated by Django 3.1.4 on 2021-02-20 09:52
from django.utils import timezone
from django.db import migrations
from django.db.migrations import RunPython

def apply_migration(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all():
        product.created_on = timezone.now()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_subscriber'),
    ]

    operations = [
        migrations.RunPython(apply_migration,)
    ]
